### PR TITLE
feat: add dockerfile

### PR DESCRIPTION
**Pull request by kwaa**
has been tested with the following `docker-compose.yml`:

```yaml
services:
  auralis:
    container_name: auralis
    build:
      context: .
      tags:
        - auralis:latest
    network_mode: host
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: cdi
            capabilities: [gpu]
            device_ids:
            - nvidia.com/gpu=all
    command: --host 127.0.0.1 --port 8001 --model AstraMindAI/xttsv2 --gpt_model AstraMindAI/xtts2-gpt --max_concurrency 8 --vllm_logging_level warn

```

### CODE REVIEW

**Comment by kwaa** [comment]
I installed `langid` in Dockerfile because this repository imports `langid`, but did not add it to the dependencies. You can update the dependency list later and remove it normally.

```diff
- # ModuleNotFoundError: No module named 'langid'
- RUN --mount=type=cache,target=/root/.cache/pip python -m pip install langid /app
+ RUN --mount=type=cache,target=/root/.cache/pip python -m pip install /app
```

**Comment by mlinmg** [comment]
Cool, thanks

**Comment by maxi1134** [comment]
I get this when trying to use this:
                                                                                                                                                                             
Error response from daemon: could not select device driver "cdi" with capabilities: [[GPU]]


Nvidia-smi works and other dockers can use the GPU

**Comment by kwaa** [comment]
> I get this when trying to use this:
>                                                                                                                                                                              
> Error response from daemon: could not select device driver "cdi" with capabilities: [[GPU]]
> 
> 
> Nvidia-smi works and other dockers can use the GPU
>                                                                                                                                                                                                                                            

You can try other ways to allocate GPUs, which may be written differently in different environments.

**Comment by maxi1134** [comment]
```
services:
  auralis:
    container_name: auralis
    build:
      context: .
      tags:
        - auralis:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/maxi1134/docker-compose/Auralis:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: --host 0.0.0.0 --port 8001 --model AstraMindAI/xttsv2 --gpt_model AstraMindAI/xtts2-gpt --max_concurrency 8 --vllm_logging_level warn

```


This worked for me

**Pull request merged**
